const assert=require('node:assert/strict'),fs=require('node:fs'),fsp=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process');
const root=process.env.STACKLINE_TEST_PACKAGE||path.resolve(__dirname,'..');const metadata=require(path.join(root,'package.json'));const cli=path.join(root,'bin/yarn.js');
const run=(args,cwd,extra={})=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,[cli,...args],{cwd,env:{...process.env,YARN_IGNORE_PATH:'1',...extra},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',d=>stdout+=d);child.stderr.on('data',d=>stderr+=d);const timer=setTimeout(()=>{child.kill('SIGTERM');reject(new Error('CLI timed out: '+args.join(' ')));},45000);child.on('exit',code=>{clearTimeout(timer);if(code===0)resolve({stdout,stderr});else reject(new Error(JSON.stringify({args,code,stdout,stderr})));});});
(async()=>{const temp=await fsp.mkdtemp(path.join(os.tmpdir(),'stackline-yarn-cli-'));let server;
try{
 assert.equal(metadata.name,'@stackline/yarn');assert.equal(metadata.version,'1.0.0');assert.deepEqual(Object.keys(metadata.bin).sort(),['yarn','yarnpkg']);
 assert.equal((await run(['--version'],temp)).stdout.trim(),metadata.version);
 const fixture=path.join(temp,'fixture'),consumer=path.join(temp,'consumer with spaces'),cache=path.join(temp,'cache');await fsp.mkdir(fixture);await fsp.mkdir(consumer);
 await fsp.writeFile(path.join(fixture,'package.json'),JSON.stringify({name:'stackline-yarn-fixture',version:'1.0.0',main:'index.js',bin:{'fixture-echo':'bin.js'}}));await fsp.writeFile(path.join(fixture,'index.js'),'module.exports = 42;\n');await fsp.writeFile(path.join(fixture,'bin.js'),'#!/usr/bin/env node\nconsole.log(process.argv.slice(2).join("|"));\n');
 const result=JSON.parse(execFileSync('npm',['pack','--ignore-scripts','--json','--pack-destination',temp],{cwd:fixture,encoding:'utf8'}));const archive=path.join(temp,(Array.isArray(result)?result[0]:Object.values(result)[0]).filename),bytes=await fsp.readFile(archive);let base;let requests=0;
 server=http.createServer((req,res)=>{requests++;if(req.url==='/stackline-yarn-fixture'){res.setHeader('content-type','application/json');res.end(JSON.stringify({name:'stackline-yarn-fixture','dist-tags':{latest:'1.0.0'},versions:{'1.0.0':{name:'stackline-yarn-fixture',version:'1.0.0',dist:{tarball:base+'/fixture.tgz',shasum:crypto.createHash('sha1').update(bytes).digest('hex'),integrity:'sha512-'+crypto.createHash('sha512').update(bytes).digest('base64')}}}}));}else if(req.url==='/fixture.tgz'){res.end(bytes);}else{res.statusCode=404;res.end('{}');}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port;
 await fsp.writeFile(path.join(consumer,'package.json'),JSON.stringify({name:'fixture-consumer',version:'1.0.0',private:true,dependencies:{'stackline-yarn-fixture':'1.0.0'},scripts:{answer:'node -e "console.log(require(\'stackline-yarn-fixture\'))"'}}));
 const flags=['--no-default-rc','--non-interactive','--ignore-scripts','--registry',base,'--cache-folder',cache];
 await run(['install',...flags],consumer);assert(requests>=2);assert.equal(require(path.join(consumer,'node_modules/stackline-yarn-fixture')),42);const lock=await fsp.readFile(path.join(consumer,'yarn.lock'),'utf8');assert.match(lock,/# yarn lockfile v1/);assert.match(lock,/integrity sha512-/);
 await new Promise(resolve=>server.close(resolve));server=null;await fsp.rm(path.join(consumer,'node_modules'),{recursive:true});await run(['install','--offline','--frozen-lockfile',...flags],consumer);assert.equal(await fsp.readFile(path.join(consumer,'yarn.lock'),'utf8'),lock);assert.equal((await run(['--no-default-rc','run','--silent','answer'],consumer)).stdout.trim(),'42');assert.match((await run(['--no-default-rc','run','--silent','fixture-echo','hello world','--flag'],consumer)).stdout,/hello world\|--flag/);
 if(process.env.STACKLINE_TEST_PACKAGE){for(const bin of ['yarn','yarnpkg']){let modules=path.dirname(root);if(path.basename(modules).startsWith('@'))modules=path.dirname(modules);const executable=path.join(modules,'.bin',bin);assert.equal(execFileSync(executable,['--version'],{cwd:temp,encoding:'utf8'}).trim(),metadata.version);}}
 console.log('CLI yarn/yarnpkg, real HTTP package install, integrity, v1 lockfile, frozen offline reinstall and script/bin arguments passed.');
}finally{if(server)await new Promise(resolve=>server.close(resolve));await fsp.rm(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
